name: flut_shop
description: Simple eshop that will work on firebase, bloc and many others packages. It will be for ios, android and web

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^3.2.0
  cached_network_image: ^3.2.0
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  firebase_storage: ^10.2.5
  cloud_firestore: ^3.1.6
  freezed_annotation: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.2
  get_it: ^7.2.0
  google_sign_in: ^5.2.1
  injectable: ^1.5.0
  json_annotation: ^4.4.0

dev_dependencies:
  auto_route_generator: ^3.2.0
  build_runner: ^2.1.7
  import_sorter: ^4.6.0
  freezed: ^1.1.0
  flutter_gen_runner: ^4.1.3
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_riverpod: ^1.0.3
  injectable_generator: ^1.5.2
  mockito: ^5.0.17
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/icons/

  fonts:
   - family: PermanentMarker
     fonts:
       - asset: fonts/PermanentMarker-Regular.ttf
   - family: NunitoSans
     fonts:
         - asset: fonts/NunitoSans-Regular.ttf
         - asset: fonts/NunitoSans-SemiBold.ttf
           weight: 600
         - asset: fonts/NunitoSans-Bold.ttf
           weight: 700

flutter_gen:
  output: lib/src/gen
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
#    flare_flutter: true
#    rive: true
