name: flut_shop
description: Simple eshop that will work on firebase and riverpod and many others packages. It will be for ios, android and web

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^3.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0

dev_dependencies:
  auto_route_generator: ^3.2.0
  build_runner: ^2.1.7
  import_sorter: ^4.6.0
  flutter_gen_runner: ^4.1.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_riverpod: ^1.0.3

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/icons/

  fonts:
   - family: PermanentMarker
     fonts:
       - asset: fonts/PermanentMarker-Regular.ttf


flutter_gen:
  output: lib/src/gen
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
#    flare_flutter: true
#    rive: true
